-- SQL скрипт инициализации БД AssetCare24 MVP
-- Версия: 1.3 (Идемпотентный / Безопасный для повторного запуска)
-- Инструкция: Можно выполнять многократно. Он создаст таблицы, если их нет, и добавит колонки, если их нет.

-- ==========================================
-- 0. Подготовка
-- ==========================================

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ==========================================
-- 1. Таблица Пользователей (users)
-- ==========================================

CREATE TABLE IF NOT EXISTS public.users (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    created_at timestamptz DEFAULT now()
);

-- Добавляем колонки безопасно (если их нет)
DO $$
BEGIN
    ALTER TABLE public.users ADD COLUMN IF NOT EXISTS phone text;
    ALTER TABLE public.users ADD COLUMN IF NOT EXISTS email text;
    ALTER TABLE public.users ADD COLUMN IF NOT EXISTS role text DEFAULT 'client' CHECK (role IN ('client', 'master', 'admin'));
    ALTER TABLE public.users ADD COLUMN IF NOT EXISTS sub_role text CHECK (sub_role IN ('tenant', 'owner', 'manager', 'worker', 'company'));
    ALTER TABLE public.users ADD COLUMN IF NOT EXISTS full_name text;
    ALTER TABLE public.users ADD COLUMN IF NOT EXISTS whatsapp_id text;
    ALTER TABLE public.users ADD COLUMN IF NOT EXISTS telegram_id text;
    ALTER TABLE public.users ADD COLUMN IF NOT EXISTS status text DEFAULT 'active' CHECK (status IN ('new', 'active', 'blocked'));
    ALTER TABLE public.users ADD COLUMN IF NOT EXISTS meta_data jsonb DEFAULT '{}'::jsonb;
    
    -- Добавляем Constraints отдельно, если их нет (для уникальности)
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'users_phone_key') THEN
        ALTER TABLE public.users ADD CONSTRAINT users_phone_key UNIQUE (phone);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'users_email_key') THEN
        ALTER TABLE public.users ADD CONSTRAINT users_email_key UNIQUE (email);
    END IF;
END $$;

ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;

-- ==========================================
-- 2. Таблица Адресов (user_addresses)
-- ==========================================

CREATE TABLE IF NOT EXISTS public.user_addresses (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    created_at timestamptz DEFAULT now()
);

DO $$
BEGIN
    ALTER TABLE public.user_addresses ADD COLUMN IF NOT EXISTS user_id uuid REFERENCES public.users(id) ON DELETE CASCADE;
    ALTER TABLE public.user_addresses ADD COLUMN IF NOT EXISTS name text;
    ALTER TABLE public.user_addresses ADD COLUMN IF NOT EXISTS postal_code text;
    ALTER TABLE public.user_addresses ADD COLUMN IF NOT EXISTS address_text text;
    ALTER TABLE public.user_addresses ADD COLUMN IF NOT EXISTS location text;
    ALTER TABLE public.user_addresses ADD COLUMN IF NOT EXISTS is_default boolean DEFAULT false;
    
    -- Исправление для NOT NULL (если нужно добавить constraint)
    -- ALTER TABLE public.user_addresses ALTER COLUMN address_text SET NOT NULL;
END $$;

ALTER TABLE public.user_addresses ENABLE ROW LEVEL SECURITY;

-- ==========================================
-- 3. Таблица Заявок (requests)
-- ==========================================

CREATE TABLE IF NOT EXISTS public.requests (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamptz DEFAULT now()
);

DO $$
BEGIN
    ALTER TABLE public.requests ADD COLUMN IF NOT EXISTS user_id uuid REFERENCES public.users(id) ON DELETE SET NULL;
    ALTER TABLE public.requests ADD COLUMN IF NOT EXISTS address_id uuid REFERENCES public.user_addresses(id) ON DELETE SET NULL;
    ALTER TABLE public.requests ADD COLUMN IF NOT EXISTS address_snapshot text;
    ALTER TABLE public.requests ADD COLUMN IF NOT EXISTS postal_code text;
    ALTER TABLE public.requests ADD COLUMN IF NOT EXISTS master_id uuid REFERENCES public.users(id) ON DELETE SET NULL;
    ALTER TABLE public.requests ADD COLUMN IF NOT EXISTS status text DEFAULT 'new' CHECK (status IN ('new', 'assigned', 'completed', 'canceled'));
    ALTER TABLE public.requests ADD COLUMN IF NOT EXISTS category text;
    ALTER TABLE public.requests ADD COLUMN IF NOT EXISTS description text;
    ALTER TABLE public.requests ADD COLUMN IF NOT EXISTS urgency text DEFAULT 'normal';
    ALTER TABLE public.requests ADD COLUMN IF NOT EXISTS admin_comment text;
    ALTER TABLE public.requests ADD COLUMN IF NOT EXISTS completed_at timestamptz;
END $$;

ALTER TABLE public.requests ENABLE ROW LEVEL SECURITY;

-- ==========================================
-- 4. Медиа файлы (request_media)
-- ==========================================

CREATE TABLE IF NOT EXISTS public.request_media (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    created_at timestamptz DEFAULT now()
);

DO $$
BEGIN
    ALTER TABLE public.request_media ADD COLUMN IF NOT EXISTS request_id bigint REFERENCES public.requests(id) ON DELETE CASCADE;
    ALTER TABLE public.request_media ADD COLUMN IF NOT EXISTS type text CHECK (type IN ('problem_photo', 'problem_audio', 'result_photo'));
    ALTER TABLE public.request_media ADD COLUMN IF NOT EXISTS bucket_path text;
    ALTER TABLE public.request_media ADD COLUMN IF NOT EXISTS public_url text;
END $$;

ALTER TABLE public.request_media ENABLE ROW LEVEL SECURITY;

-- ==========================================
-- 5. Отзывы (reviews)
-- ==========================================

CREATE TABLE IF NOT EXISTS public.reviews (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    created_at timestamptz DEFAULT now()
);

DO $$
BEGIN
    ALTER TABLE public.reviews ADD COLUMN IF NOT EXISTS request_id bigint REFERENCES public.requests(id) ON DELETE CASCADE;
    ALTER TABLE public.reviews ADD COLUMN IF NOT EXISTS rating int CHECK (rating >= 1 AND rating <= 5);
    ALTER TABLE public.reviews ADD COLUMN IF NOT EXISTS comment text;
END $$;

ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;

-- ==========================================
-- 6. Машина состояний бота (bot_states)
-- ==========================================

CREATE TABLE IF NOT EXISTS public.bot_states (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    updated_at timestamptz DEFAULT now()
);

DO $$
BEGIN
    ALTER TABLE public.bot_states ADD COLUMN IF NOT EXISTS user_phone text;
    ALTER TABLE public.bot_states ADD COLUMN IF NOT EXISTS messenger_id text;
    ALTER TABLE public.bot_states ADD COLUMN IF NOT EXISTS platform text DEFAULT 'whatsapp';
    ALTER TABLE public.bot_states ADD COLUMN IF NOT EXISTS state text DEFAULT 'start';
    ALTER TABLE public.bot_states ADD COLUMN IF NOT EXISTS context jsonb DEFAULT '{}'::jsonb;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'bot_states_messenger_id_key') THEN
        ALTER TABLE public.bot_states ADD CONSTRAINT bot_states_messenger_id_key UNIQUE (messenger_id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'bot_states_user_phone_key') THEN
        ALTER TABLE public.bot_states ADD CONSTRAINT bot_states_user_phone_key UNIQUE (user_phone);
    END IF;
END $$;

ALTER TABLE public.bot_states ENABLE ROW LEVEL SECURITY;

-- ==========================================
-- 7. Представления (Views) - Пересоздаем всегда
-- ==========================================

DROP VIEW IF EXISTS view_dispatcher_dashboard;
CREATE OR REPLACE VIEW view_dispatcher_dashboard AS
SELECT
    r.id,
    r.status,
    r.created_at,
    r.postal_code,
    r.category,
    r.address_snapshot as address,
    u.phone as client_phone,
    u.full_name as client_name,
    u.sub_role as client_type,
    m.full_name as master_name
FROM requests r
JOIN users u ON r.user_id = u.id
LEFT JOIN users m ON r.master_id = m.id
WHERE r.status IN ('new', 'assigned');

DROP VIEW IF EXISTS view_master_stats;
CREATE OR REPLACE VIEW view_master_stats AS
SELECT
    m.full_name,
    COUNT(r.id) as total_jobs,
    AVG(rev.rating)::numeric(10,2) as avg_rating
FROM users m
JOIN requests r ON r.master_id = m.id
LEFT JOIN reviews rev ON rev.request_id = r.id
WHERE m.role = 'master' AND r.status = 'completed'
GROUP BY m.id, m.full_name;
